name: Node.js CI with MySQL

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          #MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
          MYSQL_USER: ${{ secrets.DATABASE_USER }}
          MYSQL_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Choose your desired Node.js version
    
    - name: Start MySQL Service
      run: sudo service mysql start

    - name: check MySQL from ps
      run: sudo ps -ef | grep mysql
    
    - name: 
    
    - name: Verify MySQL Port
      run: sudo netstat -tuln | grep 3306
    
    - name: check ip address
      run: ip address

    #- name: Run Database Health Check
    #  run: |
    #    # Check database health using mysqladmin command
    #    mysqladmin ping -h ${{ secrets.DATABASE_HOST }} -u ${{ secrets.DATABASE_USER }} -p${{ secrets.DATABASE_PASSWORD }} -S /var/run/mysqld/mysqld.sock test

    - name: Debug MySQL Status
      run: mysql -u ${{ secrets.DATABASE_USER }} -p${{ secrets.DATABASE_PASSWORD }} -e "SHOW STATUS"

    - name: Install dependencies
      run: npm install

    - name: Install Mocha globally
      run: npm install -g mocha

    - name: Run Database Health Check
      run: |
        # Check database health using mysqladmin command
        mysqladmin ping -h localhost -u ${{ secrets.DATABASE_USER }} -p${{ secrets.DATABASE_PASSWORD }} test

    - name: Run  tests
      run: npm test