name: Integ-Testing


on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    # - name: Wait for MySQL to be ready
    #   run: |
    #     n=0
    #     until [ $n -ge 5 ]
    #     do
    #       npm run db:migrate:up # Replace with your database migration command
    #       [ $? -eq 0 ] && break
    #       n=$[$n+1]
    #       sleep 15
    #     done

    - name: Run Tests
      env:
        DB_HOST: localhost
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: Test@123
        DB_NAME: test
      run: npm test
