name: CI/CD test

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: installing node
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: install and run
        run: npm install

      - name: install mysql db with required configs
      - uses: mirromutth/mysql-action@v1.1
        with: 
          host port: 3306
          mysql version: 5.7
          mysql database: 'test'
          mysql root password: 'Test@123'
          mysql user: 'root'
          mysql password: 'Test@123'
