name: Integration-Testing

on:
  pull_request:
    branches:
      -main

jobs:
  integration-testing:
    runs-on: ubuntu-latest
    name: Setup Node Environment and test npm
    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          mysql version: '5.7'
          mysql database: 'testdb'
          mysql root password: 'Test@123'
          mysql user: root

      - name: Setup Node js
        uses: actions/checkout@v3
        uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - name: Install Node packages
        run: npm ci
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: 'Test@123'
          DB_NAME: testdb
        run: npm test

