name: CI/CD test

on:
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: installing node
      uses: actions/setup-node@v3
      with: 
        node-version: 18
    - name: install and run
      run: |
        npm ci
        npm test