name: MySQL GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup MySQL
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port 3306 --user=root --password=password -e 'CREATE DATABASE IF NOT EXISTS test_db;'



    - name: Checkout code

      uses: actions/checkout@v2

 

    - name: Set up Node.js

      uses: actions/setup-node@v2

      with:

        node-version: '14'

 

    - name: Install Dependencies

      run: npm install

 

    # - name: Wait for MySQL to be ready

    #   run: |

    #     n=0

    #     until [ $n -ge 5 ]

    #     do

    #       npm run db:migrate:up # Replace with your database migration command

    #       [ $? -eq 0 ] && break

    #       n=$[$n+1]

    #       sleep 15

    #     done

    - name: install mocha 
      run : npm install mocha


    - name: Run Tests

      env:

        DB_HOST: 127.0.0.1

        DB_PORT: 3306

        DB_USER: root

        DB_PASSWORD: password

        DB_NAME: test_db

      run: npm test
      



      