name: CI/CD test

on:
  pull_request:
    branches:
      - main

jobs:
  Test-Integration:
    runs-on: ubuntu-latest
    env:
      database: test
      username: root
      password: root
      host: 127.0.0.1
      PORT: 8080
    services:
      mysqldb:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=30s --health-retries=5

    steps:
      - name: Checkout Webapp Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: downloading npm packages
        run: npm install

      - name: Verify MySQL connection from container 
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          sudo mysql --host 127.0.0.1 -uroot -proot -e "SHOW DATABASES"
      
      - name: start node application
        run: node app.js