name: Node.js with MariaDB CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: 'Test@123'
          MYSQL_USER: root
          MYSQL_PASSWORD: 'Test@123'
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Start MariaDB
      run: |
        docker run -d --name mariadb \
          -e MYSQL_ROOT_PASSWORD='Test@123' \
          -e MYSQL_USER=root \
          -e MYSQL_PASSWORD='Test@123' \
          -e MYSQL_DATABASE=test \
          -p 3306:3306 \
          mariadb:latest
      continue-on-error: true # Continue even if the container startup fails

      - name: Wait for MariaDB to be healthy
      run: |
        timeout 60 bash -c \
          'while [[ "$(docker inspect -f {{.State.Health.Status}} mariadb)" != "healthy" ]]; do
            sleep 1; 
            done'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build and Deploy
        run: |
          # Replace with your build and deployment commands
          npm test
          # Example deployment command: npm run deploy

      - name: Wait for MariaDB to be healthy
        run: docker wait mariadb

      - name: Cleanup MariaDB container
        run: docker stop mariadb
