name: CI/CD test

on:
  pull_request:
    branches:
      - main

jobs:
  Test-Integration:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      PORT: ${{ secrets.PORT }}
      MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
    services:
      mysqldb:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Test@123
          MYSQL_DATABASE: test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=30s --health-retries=5

    steps:
      - name: Checkout Webapp Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: downloading npm packages
        run: npm install

      - name: Verify MySQL connection from container 
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          sudo mysql --host ${{ secrets.DATABASE_HOST }} -u${{ secrets.DATABASE_USER }} -p${{ secrets.DATABASE_PASSWORD }} -e "SHOW DATABASES"
      
      #- name: install sequelize and mysql2
      #  run: npm install sequelize mysql2 
      
      - name: start node application
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          PORT: ${{ secrets.PORT }}
        run: npm test