name: CI/CD test

on:
  pull_request:
    branches:
      - main

jobs:
  Test-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
            
      - name: Echo the result of 1 + 1
        run: echo $((1 + 1))

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      
      - name: downloading npm packages
        run: npm install
      
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      - name: creating mysql configurations
        uses: mirromutth/mysql-action@v1.1
        with: 
      
      - name: install mocha
        run: npm install mocha
      
      - name: starting the webapp application
        run: npm test
        env:
          DATABASE_NAME: sys
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DATABASE_HOST: 127.0.0.1
          PORT: 8080

            
