name: Node.js

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: webapp test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.2.0]

    steps:
    - uses: actions/checkout@v3
    - name: Wait for MySQL to become available
      run: sudo systemctl start mysql && sudo mysql -u root -pTest@123 -e "CREATE DATABASE test"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install mocha
    - run: npm ci
    - run: ip address
    - run: npm run test