name: CI/CD test

on:
  pull_request:
    branches:
      - main

jobs:
  Test-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
            
      - name: Echo the result of 1 + 1
        run: echo $((1 + 1))

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      
      - name: downloading npm packages
        run: npm install

      - name: creating mysql configurations
        uses: mirromutth/mysql-action@v1.1
        with: 
          host: 3306
          mysql version: 5.7
          mysql database: 'test'
          mysql root password: 'Test@123'
          mysql user: 'root'
          mysql password: 'Test@123'
      
      - name: install mocha
        run: npm install mocha
      
      - name: starting the webapp application
        run: npm test
        env:
          DATABASE_NAME: test
          DATABASE_USER: root
          DATABASE_PASSWORD: Test@123
          DATABASE_HOST: 127.0.0.1
          PORT: 8080

            
