name: Node.js

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: webapp test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Test@123
          MYSQL_DATABASE: test # Specify the name of the database to be created here
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: [19.2.0]

    steps:
    - uses: actions/checkout@v3
    - name: Wait for MySQL to become available
      run: |
        for i in {1..30}; do
          if echo 'SELECT 1' | mysql --host=127.0.0.1 --user=root --password=Test@123 &> /dev/null; then
            break
          fi
          echo "Waiting for MySQL..."
          sleep 1
        done
    - name: Check and verify database existence
      run: |
        echo 'SHOW DATABASES;' | mysql --host=127.0.0.1 --user=root --password=Test@123 | grep test
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install mocha
    - run: npm ci
    - run: npm run test