name: Packer Validation

on:
  pull_request:
    branches:
      - main
env:
  PRODUCT_VERSION: "1.9.4"
  AMI_REGION: ${{ vars.AMI_REGION }}
  LOGIN_USERNAME: ${{ vars.LOGIN_USERNAME }}
  INSTANCE_TYPE: ${{ vars.INSTANCE_TYPE }}
  AMIOWNERID: ${{ vars.AMIOWNERID }}
  AMISHAREDOWNER: ${{ vars.AMISHAREDOWNER }}
  DATABASE_HOST: ${{ vars.DATABASE_HOST }}
  DATABASE_USER: ${{ vars.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
  DATABASE_NAME: ${{ vars.DATABASE_NAME }}


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: write variables into env file
        run: |
          echo "LOCAL_DATABASE_HOST: ${{ vars.LOCAL_DATABASE_HOST }}" >> .env
          echo "DATABASE_HOST: ${{vars.DATABASE_HOST}}" >> .env
          echo "ROOT_DATABASE_USER: ${{ vars.ROOT_DATABASE_USER }}" >> .env
          echo "ROOT_DATABASE_PASSWORD: ${{ vars.ROOT_DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_USER: ${{vars.DATABASE_USER}}" >> .env
          echo "DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_NAME: ${{ vars.DATABASE_NAME }}" >> .env
          echo "DATABASE_HOST: ${{ vars.DATABASE_HOST }}" >> .env
          echo "below are environment variables"
          cat .env
        shell: bash

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      
      - name: zip the file
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'webapp.zip'
          exclusions: '*.git* /*node_modules/* '

      - name: Run `packer init`
        id: init
        run: "packer init ."

      - name: Run packer fmt
        run: |
          if ! packer fmt -check aws-ubuntu.pkr.hcl; then
            echo "Packer template is not properly formatted. Please run 'packer fmt' locally and commit the changes."
            exit 1
          fi

      - name: Run packer validate
        run: |
          if ! packer validate aws-ubuntu.pkr.hcl; then
            echo "Packer template validation failed. Please fix the issues and try again."
            exit 1
          fi